/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    IconsArrowDown: typeof import('./src/components/icons/ArrowDown.vue')['default']
    IconsArrowLeft: typeof import('./src/components/icons/ArrowLeft.vue')['default']
    IconsArrowLeftLine: typeof import('./src/components/icons/ArrowLeftLine.vue')['default']
    IconsArrowRight: typeof import('./src/components/icons/ArrowRight.vue')['default']
    IconsArrowRightLine: typeof import('./src/components/icons/ArrowRightLine.vue')['default']
    IconsArrowUp: typeof import('./src/components/icons/ArrowUp.vue')['default']
    IconsBed: typeof import('./src/components/icons/Bed.vue')['default']
    IconsCar: typeof import('./src/components/icons/Car.vue')['default']
    IconsCheck: typeof import('./src/components/icons/Check.vue')['default']
    IconsClose: typeof import('./src/components/icons/Close.vue')['default']
    IconsLine: typeof import('./src/components/icons/Line.vue')['default']
    IconsLuxuryCar: typeof import('./src/components/icons/LuxuryCar.vue')['default']
    IconsMenu: typeof import('./src/components/icons/Menu.vue')['default']
    IconsMinus: typeof import('./src/components/icons/Minus.vue')['default']
    IconsPerson: typeof import('./src/components/icons/Person.vue')['default']
    IconsPlus: typeof import('./src/components/icons/Plus.vue')['default']
    IconsProfile: typeof import('./src/components/icons/Profile.vue')['default']
    IconsSize: typeof import('./src/components/icons/Size.vue')['default']
    IconsTrain: typeof import('./src/components/icons/Train.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    LayoutFooter: typeof import('./src/components/layout/Footer.vue')['default']
    LayoutNavbar: typeof import('./src/components/layout/Navbar.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./src/components/Tab.vue')['default']
  }
}
